export interface SongLine {
  chords: string[];
  syllables: string[];
}

export interface Song {
  id: string;
  title: string;
  artist: string;
  album: string;
  mins: string;
  bpm: number;
  key: string;
  difficulty: string;
  difficultyDots: number;
  chords: string[];
  strum: string;
  genre: string;
  color: string;
  gradient: string[];
  lines?: SongLine[];
}

export const SONGS: Song[] = [
  // ─── EASY (3–4 open chords) ────────────────────────────────────────────────

  {
    id: 'knockin-on-heavens-door',
    title: "Knockin' on Heaven's Door",
    artist: 'Bob Dylan',
    album: 'Pat Garrett & Billy the Kid',
    mins: '2:31',
    bpm: 70,
    key: 'G',
    difficulty: 'Easy',
    difficultyDots: 1,
    chords: ['G', 'D', 'Am', 'C'],
    strum: 'D D DU',
    genre: 'Folk Rock',
    color: '#8B5E3C',
    gradient: ['#8B5E3C', '#3d2510'],
  },
  {
    id: 'stand-by-me',
    title: 'Stand by Me',
    artist: 'Ben E. King',
    album: 'Don\'t Play That Song!',
    mins: '2:57',
    bpm: 116,
    key: 'A',
    difficulty: 'Easy',
    difficultyDots: 1,
    chords: ['A', 'F#m', 'D', 'E'],
    strum: 'D D D DU',
    genre: 'R&B / Soul',
    color: '#2e5fa3',
    gradient: ['#2e5fa3', '#0f2040'],
  },
  {
    id: 'bad-moon-rising',
    title: 'Bad Moon Rising',
    artist: 'Creedence Clearwater Revival',
    album: 'Green River',
    mins: '2:19',
    bpm: 178,
    key: 'D',
    difficulty: 'Easy',
    difficultyDots: 1,
    chords: ['D', 'A', 'G'],
    strum: 'D DU UDU',
    genre: 'Classic Rock',
    color: '#c47c1a',
    gradient: ['#c47c1a', '#5a3205'],
  },
  {
    id: 'love-me-do',
    title: 'Love Me Do',
    artist: 'The Beatles',
    album: 'Please Please Me',
    mins: '2:22',
    bpm: 140,
    key: 'G',
    difficulty: 'Easy',
    difficultyDots: 1,
    chords: ['G', 'C', 'D'],
    strum: 'D D D D',
    genre: 'Classic Rock',
    color: '#b03a2e',
    gradient: ['#b03a2e', '#4a1010'],
  },
  {
    id: 'take-me-home-country-roads',
    title: 'Take Me Home, Country Roads',
    artist: 'John Denver',
    album: 'Poems, Prayers & Promises',
    mins: '3:08',
    bpm: 82,
    key: 'G',
    difficulty: 'Easy',
    difficultyDots: 1,
    chords: ['G', 'Em', 'C', 'D'],
    strum: 'D DU DU',
    genre: 'Country / Folk',
    color: '#4a7c59',
    gradient: ['#4a7c59', '#1a3520'],
  },
  {
    id: 'good-riddance',
    title: 'Good Riddance (Time of Your Life)',
    artist: 'Green Day',
    album: 'Nimrod',
    mins: '2:34',
    bpm: 95,
    key: 'G',
    difficulty: 'Easy',
    difficultyDots: 1,
    chords: ['G', 'Cadd9', 'D', 'Em'],
    strum: 'D DU DU',
    genre: 'Pop Punk',
    color: '#2d7d46',
    gradient: ['#2d7d46', '#0d3018'],
  },
  {
    id: 'brown-eyed-girl',
    title: 'Brown Eyed Girl',
    artist: 'Van Morrison',
    album: "Blowin' Your Mind!",
    mins: '3:05',
    bpm: 150,
    key: 'G',
    difficulty: 'Easy',
    difficultyDots: 1,
    chords: ['G', 'C', 'D', 'Em'],
    strum: 'D DU DU',
    genre: 'Rock',
    color: '#8B4513',
    gradient: ['#8B4513', '#3d1a05'],
  },
  {
    id: 'wagon-wheel',
    title: 'Wagon Wheel',
    artist: 'Old Crow Medicine Show',
    album: 'O.C.M.S.',
    mins: '4:42',
    bpm: 76,
    key: 'G',
    difficulty: 'Easy',
    difficultyDots: 1,
    chords: ['G', 'D', 'Em', 'C'],
    strum: 'D D DU DU',
    genre: 'Country / Folk',
    color: '#b07d2e',
    gradient: ['#b07d2e', '#4d3310'],
  },
  {
    id: 'simple-man',
    title: 'Simple Man',
    artist: 'Lynyrd Skynyrd',
    album: 'Pronounced Leh-nerd Skin-nerd',
    mins: '5:55',
    bpm: 65,
    key: 'C',
    difficulty: 'Easy',
    difficultyDots: 1,
    chords: ['C', 'G', 'Am'],
    strum: 'D D DU DU',
    genre: 'Southern Rock',
    color: '#5a4a8a',
    gradient: ['#5a4a8a', '#221a40'],
  },
  {
    id: 'ho-hey',
    title: 'Ho Hey',
    artist: 'The Lumineers',
    album: 'The Lumineers',
    mins: '2:43',
    bpm: 80,
    key: 'C',
    difficulty: 'Easy',
    difficultyDots: 1,
    chords: ['F', 'C', 'Am', 'G'],
    strum: 'D D D D',
    genre: 'Indie Folk',
    color: '#c97a2e',
    gradient: ['#c97a2e', '#5a3010'],
  },
  {
    id: 'free-fallin',
    title: "Free Fallin'",
    artist: 'Tom Petty',
    album: 'Full Moon Fever',
    mins: '4:13',
    bpm: 84,
    key: 'F',
    difficulty: 'Easy',
    difficultyDots: 1,
    chords: ['F', 'Bb', 'C'],
    strum: 'D DU UDU',
    genre: 'Classic Rock',
    color: '#3a6ea8',
    gradient: ['#3a6ea8', '#12274a'],
  },
  {
    id: 'wish-you-were-here',
    title: 'Wish You Were Here',
    artist: 'Pink Floyd',
    album: 'Wish You Were Here',
    mins: '5:35',
    bpm: 63,
    key: 'G',
    difficulty: 'Easy',
    difficultyDots: 1,
    chords: ['Em7', 'G', 'A7sus4', 'C', 'D'],
    strum: 'D D DU',
    genre: 'Classic Rock',
    color: '#2e7d8a',
    gradient: ['#2e7d8a', '#0d2f35'],
  },
  {
    id: 'wonderwall',
    title: 'Wonderwall',
    artist: 'Oasis',
    album: '(What\'s the Story) Morning Glory?',
    mins: '4:18',
    bpm: 87,
    key: 'F#m',
    difficulty: 'Easy',
    difficultyDots: 1,
    chords: ['Em7', 'G', 'Dsus4', 'A7sus4'],
    strum: 'D DU DU DU',
    genre: 'Britpop',
    color: '#d4a017',
    gradient: ['#d4a017', '#5e4208'],
  },
  {
    id: 'fast-car',
    title: 'Fast Car',
    artist: 'Tracy Chapman',
    album: 'Tracy Chapman',
    mins: '4:57',
    bpm: 100,
    key: 'C',
    difficulty: 'Easy',
    difficultyDots: 1,
    chords: ['Cadd9', 'G', 'Em', 'D'],
    strum: 'D D DU DU',
    genre: 'Folk Rock',
    color: '#556b2f',
    gradient: ['#556b2f', '#1e2810'],
  },

  // ─── MEDIUM (5–6 chords, some barre chords) ───────────────────────────────

  {
    id: 'sweet-home-alabama',
    title: 'Sweet Home Alabama',
    artist: 'Lynyrd Skynyrd',
    album: 'Second Helping',
    mins: '4:44',
    bpm: 98,
    key: 'D',
    difficulty: 'Medium',
    difficultyDots: 2,
    chords: ['D', 'C', 'G', 'F'],
    strum: 'D DU UDU',
    genre: 'Southern Rock',
    color: '#a03535',
    gradient: ['#a03535', '#401010'],
  },
  {
    id: 'creep',
    title: 'Creep',
    artist: 'Radiohead',
    album: 'Pablo Honey',
    mins: '3:58',
    bpm: 92,
    key: 'G',
    difficulty: 'Medium',
    difficultyDots: 2,
    chords: ['G', 'B', 'C', 'Cm'],
    strum: 'D D D DU',
    genre: 'Alternative Rock',
    color: '#3a3a6e',
    gradient: ['#3a3a6e', '#111130'],
  },
  {
    id: 'have-you-ever-seen-the-rain',
    title: 'Have You Ever Seen the Rain?',
    artist: 'Creedence Clearwater Revival',
    album: 'Pendulum',
    mins: '2:41',
    bpm: 116,
    key: 'C',
    difficulty: 'Medium',
    difficultyDots: 2,
    chords: ['C', 'Am', 'G', 'F'],
    strum: 'D DU UDU',
    genre: 'Classic Rock',
    color: '#5b8ca6',
    gradient: ['#5b8ca6', '#1a3545'],
  },
  {
    id: 'learning-to-fly',
    title: 'Learning to Fly',
    artist: 'Tom Petty',
    album: 'Into the Great Wide Open',
    mins: '3:57',
    bpm: 117,
    key: 'C',
    difficulty: 'Medium',
    difficultyDots: 2,
    chords: ['F', 'C', 'Am', 'G'],
    strum: 'D DU DU',
    genre: 'Classic Rock',
    color: '#6a8aaa',
    gradient: ['#6a8aaa', '#223344'],
  },
  {
    id: 'heart-of-gold',
    title: 'Heart of Gold',
    artist: 'Neil Young',
    album: 'Harvest',
    mins: '3:04',
    bpm: 71,
    key: 'E',
    difficulty: 'Medium',
    difficultyDots: 2,
    chords: ['Em', 'D', 'G', 'C', 'Am'],
    strum: 'D D DU',
    genre: 'Folk Rock',
    color: '#c9a832',
    gradient: ['#c9a832', '#5a450a'],
  },
  {
    id: 'one',
    title: 'One',
    artist: 'U2',
    album: 'Achtung Baby',
    mins: '4:36',
    bpm: 89,
    key: 'Am',
    difficulty: 'Medium',
    difficultyDots: 2,
    chords: ['Am', 'D', 'F', 'G', 'C'],
    strum: 'D D DU DU',
    genre: 'Rock',
    color: '#8a5aa0',
    gradient: ['#8a5aa0', '#351d40'],
  },
  {
    id: 'summer-of-69',
    title: 'Summer of 69',
    artist: 'Bryan Adams',
    album: 'Reckless',
    mins: '3:35',
    bpm: 138,
    key: 'D',
    difficulty: 'Medium',
    difficultyDots: 2,
    chords: ['D', 'A', 'G', 'Bm', 'F', 'Bb', 'C'],
    strum: 'DU DU DU DU',
    genre: 'Classic Rock',
    color: '#c44a2a',
    gradient: ['#c44a2a', '#501508'],
  },
  {
    id: 'mr-jones',
    title: 'Mr. Jones',
    artist: 'Counting Crows',
    album: 'August and Everything After',
    mins: '4:33',
    bpm: 135,
    key: 'Am',
    difficulty: 'Medium',
    difficultyDots: 2,
    chords: ['Am', 'F', 'Dm', 'G', 'C'],
    strum: 'D DU UDU',
    genre: 'Alternative Rock',
    color: '#7a5a3a',
    gradient: ['#7a5a3a', '#302010'],
  },
  {
    id: 'mary-janes-last-dance',
    title: "Mary Jane's Last Dance",
    artist: 'Tom Petty',
    album: 'Greatest Hits',
    mins: '4:34',
    bpm: 101,
    key: 'Am',
    difficulty: 'Medium',
    difficultyDots: 2,
    chords: ['Am', 'G', 'D', 'Em7'],
    strum: 'D DU UDU',
    genre: 'Classic Rock',
    color: '#3a5a8a',
    gradient: ['#3a5a8a', '#101f35'],
  },
  {
    id: 'rockin-in-the-free-world',
    title: "Rockin' in the Free World",
    artist: 'Neil Young',
    album: 'Freedom',
    mins: '4:35',
    bpm: 130,
    key: 'Em',
    difficulty: 'Medium',
    difficultyDots: 2,
    chords: ['Em', 'D', 'C', 'G', 'A'],
    strum: 'DU DU DU',
    genre: 'Rock',
    color: '#4a8a5a',
    gradient: ['#4a8a5a', '#162a1e'],
  },
  {
    id: 'i-wont-back-down',
    title: "I Won't Back Down",
    artist: 'Tom Petty',
    album: 'Full Moon Fever',
    mins: '2:56',
    bpm: 96,
    key: 'E',
    difficulty: 'Easy',
    difficultyDots: 1,
    chords: ['Em', 'D', 'G', 'C'],
    strum: 'D D DU',
    genre: 'Classic Rock',
    color: '#7a4a6a',
    gradient: ['#7a4a6a', '#2e1628'],
  },
  {
    id: 'perfect',
    title: 'Perfect',
    artist: 'Ed Sheeran',
    album: '÷ (Divide)',
    mins: '4:23',
    bpm: 95,
    key: 'G',
    difficulty: 'Easy',
    difficultyDots: 1,
    chords: ['G', 'Em', 'C', 'D'],
    strum: 'D D DU UDU',
    genre: 'Pop',
    color: '#e84393',
    gradient: ['#e84393', '#6a0a3a'],
  },
  {
    id: 'with-or-without-you',
    title: 'With or Without You',
    artist: 'U2',
    album: 'The Joshua Tree',
    mins: '4:56',
    bpm: 113,
    key: 'D',
    difficulty: 'Easy',
    difficultyDots: 1,
    chords: ['D', 'A', 'Bm', 'G'],
    strum: 'D D D DU',
    genre: 'Rock',
    color: '#3a5a9a',
    gradient: ['#3a5a9a', '#101d3a'],
  },
  {
    id: 'every-rose-has-its-thorn',
    title: 'Every Rose Has Its Thorn',
    artist: 'Poison',
    album: 'Open Up and Say... Ahh!',
    mins: '4:20',
    bpm: 104,
    key: 'G',
    difficulty: 'Medium',
    difficultyDots: 2,
    chords: ['G', 'Cadd9', 'D', 'Em', 'C'],
    strum: 'D DU DU',
    genre: 'Rock Ballad',
    color: '#c43a7a',
    gradient: ['#c43a7a', '#4d0f2e'],
  },
];

export interface ChordShape {
  frets: number[];
  fingers: number[];
  barre?: number;
}

export const CHORD_SHAPES: Record<string, ChordShape> = {
  // Open chords
  G:      { frets: [3, 2, 0, 0, 0, 3],    fingers: [2, 1, 0, 0, 0, 3] },
  C:      { frets: [-1, 3, 2, 0, 1, 0],   fingers: [0, 3, 2, 0, 1, 0] },
  D:      { frets: [-1, -1, 0, 2, 3, 2],  fingers: [0, 0, 0, 1, 3, 2] },
  Em:     { frets: [0, 2, 2, 0, 0, 0],    fingers: [0, 2, 3, 0, 0, 0] },
  Am:     { frets: [-1, 0, 2, 2, 1, 0],   fingers: [0, 0, 2, 3, 1, 0] },
  A:      { frets: [-1, 0, 2, 2, 2, 0],   fingers: [0, 0, 1, 2, 3, 0] },
  E:      { frets: [0, 2, 2, 1, 0, 0],    fingers: [0, 2, 3, 1, 0, 0] },
  Dm:     { frets: [-1, -1, 0, 2, 3, 1],  fingers: [0, 0, 0, 2, 3, 1] },
  // Barre / intermediate chords
  F:      { frets: [1, 3, 3, 2, 1, 1],    fingers: [1, 3, 4, 2, 1, 1], barre: 1 },
  Bb:     { frets: [1, 3, 3, 3, 1, 1],    fingers: [1, 2, 3, 4, 1, 1], barre: 1 },
  B:      { frets: [-1, 2, 4, 4, 4, 2],   fingers: [0, 1, 2, 3, 4, 1], barre: 2 },
  Cm:     { frets: [-1, 3, 5, 5, 4, 3],   fingers: [0, 1, 3, 4, 2, 1], barre: 3 },
  'F#m':  { frets: [2, 4, 4, 2, 2, 2],    fingers: [1, 3, 4, 1, 1, 1], barre: 2 },
  Bm:     { frets: [-1, 2, 4, 4, 3, 2],   fingers: [0, 1, 3, 4, 2, 1], barre: 2 },
  // Suspended / extended open chords
  Em7:    { frets: [0, 2, 2, 0, 3, 0],    fingers: [0, 2, 3, 0, 4, 0] },
  Dsus4:  { frets: [-1, -1, 0, 2, 3, 3],  fingers: [0, 0, 0, 1, 2, 3] },
  A7sus4: { frets: [-1, 0, 2, 0, 3, 0],   fingers: [0, 0, 2, 0, 3, 0] },
  Cadd9:  { frets: [-1, 3, 2, 0, 3, 0],   fingers: [0, 3, 2, 0, 4, 0] },
};
